print('{}Quando você nasceu?'.format('\33[32m'))
dia=input('{}Dia = '.format('\33[0;31m'))
mes=input('Mes = ')
ano=input('Ano = ')
print('{}Você nasceu no dia {} de {} do ano {}'.format('\33[4;34m',dia,mes,ano))
